/* Generated by bin2c, do not edit manually */
#ifndef A_H
#define A_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define A_size 48001
extern const int16_t A[48001];

#endif    /* __A_16KHz_h_included */
