/* Generated by bin2c, do not edit manually */
#ifndef B_h
#define B_h

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define B_size 48001
extern const int16_t B[48001];

#endif    /* __A_16KHz_h_included */
