/* Generated by bin2c, do not edit manually */
#ifndef C_H
#define C_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define C_size 48001
extern const int16_t C[48001];

#endif    /* __A_16KHz_h_included */
