/* Generated by bin2c, do not edit manually */
#ifndef D_H
#define D_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define D_size 48001
extern const int16_t D[48001];

#endif    /* __A_16KHz_h_included */
