/* Generated by bin2c, do not edit manually */
#ifndef E_H
#define E_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define E_size 48001
extern const int16_t E[48001];

#endif    /* __A_16KHz_h_included */
