/* Generated by bin2c, do not edit manually */
#ifndef F_H
#define F_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define F_size 48001
extern const int16_t F[48001];

#endif    /* __A_16KHz_h_included */
