/* Generated by bin2c, do not edit manually */
#ifndef G_H
#define G_H

#include <stdint.h>

/* Contents of file .\A_16KHz.wav */
#define G_size 48001
extern const int16_t G[48001];

#endif    /* __A_16KHz_h_included */
